<?php

/**
 * @file
 * Install, update and uninstall functions for the Date Migrate Example module.
 */

/**
 * Implements hook_enable().
 */
function date_migrate_example_enable() {
  Migration::registerMigration('DateExampleMigration', 'DateExample', array('group_name' => 'Example'));
}

/**
 * Implements hook_disable().
 */
function date_migrate_example_disable() {
  Migration::deregisterMigration('DateExample');
}
